# Generated by Django 4.1 on 2022-10-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/food/%y%m%d'),
        ),
    ]
