# Generated by Django 4.1 on 2022-10-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0003_alter_food_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.TextField(choices=[('Fries', 'Fries'), ('Rice/Spaghetti', 'Rice/Spaghetti'), ('Soup', 'Soup')]),
        ),
    ]
