# Generated by Django 4.1 on 2022-10-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestOrder',
        ),
    ]
